### ISSUE TITLE
Any release coming that includes the slave_lag throttler?

### ISSUE THREAD

**Issue by notnmeyer** [soundcloud/lhm#122]
Hi! Are there any plans for a new versioned release that includes the slave_lag throttler that's currently in Master?

**Comment by arthurnn** [comment]
@notnmeyer we are in process of make it a little better . and we are also testing it in Shopify. as soon as we have it 100% working. I will let you know, and release a beta version of LHM
cc @camilo @jordanwheeler

**Comment by christophermanning** [comment]
For the final 3.0.0 release, are there any issues or other work the community can help with? Tagging or adding issues with the 3.0.0 milestone or adding 'needs review/help/comments' labels to issues can help focus efforts. Thanks!

**Comment by camilo** [comment]
@arthurnn working nicely here :shipit:

**Comment by arthurnn** [comment]
is it? awesome.. 
Are you using only the slave lag delay ? I was wondering that we will need a way to combine that one with the time one.

**Comment by camilo** [comment]
IIRC just slave lag @jordanwheeler will know fo sho

**Comment by notnmeyer** [comment]
i'm no longer using this. feel free to reopen if it's useful for tracking or something.
