### ISSUE TITLE
How well does LHM play with Galera clusters?

### ISSUE THREAD

**Issue by HHRy** [soundcloud/lhm#124]
Hi there!

I'm currently trying to solve some pains we're having at work with DDL migrations on really huge tables. We've got a reasonably standard 3 node Galaera cluster set up. Right now, we're running these migrations by hand using RSU mode and a console, since the default TOI method really screws us up.

Would you be able to please answer these two questions?

Has LHM been tested with Galera clusters, and is it still able to play nice and be all non-locky while being executed in TOI mode?

How well does it cope with writes coming to the table being altered while the migration is in progress? I assume it behaves comparably to pt-online-schema-change?

Thanks so much for your time!

<3 Ry

**Comment by evantahler** [comment]
We use LHM on Percona/Gallera Cluster with no problems.  Writes/Updates are obviously slower as you need to wait for all nodes to ACK them, but it works as expected.
