### ISSUE TITLE
Flag the repo as unmaintained?

### ISSUE THREAD

**Issue by tdeo** [soundcloud/lhm#153]
It seems like nothing is changing anymore, I've got an issue about data loss (https://github.com/soundcloud/lhm/issues/126) that has been opened for almost 3 years and PRs (https://github.com/soundcloud/lhm/pull/127 and https://github.com/soundcloud/lhm/pull/134) to fix this, but nothing has received attention. This repo should maybe be flagged as unmaintained in its Readme?

**Comment by grobie** [comment]
Good news, I've merged all your PRs and closed the issues, sorry for not doing that earlier. Bad news, as you've already noticed, is that none of us at SoundCloud has time to maintain this repo. We used to have an outside collaborator from GtiHub Inc. as an active maintainer, but I guess they also shifted focus.

Would you be interested in taking over maintainership?

**Comment by jrgifford** [comment]
@grobie Have you talked to anyone at Shopify? They seem to have a fairly active fork over at https://github.com/shopify/lhm

**Comment by epugh** [comment]
Would be nice if the README pointed to the shopify fork....!

**Comment by gdubicki** [comment]
Please see https://github.com/soundcloud/lhm/issues/168.
