### ISSUE TITLE
Feature request: `max_lag` and/or `max_load` options

### ISSUE THREAD

**Issue by airhorns** [soundcloud/lhm#23]
Do you think it would be difficult to add options to LHM to allow for monitoring and adjustment of load if slave lag or server load grows above a threshold? At Shopify we see our replication lag grow very large and quite quickly for our bigger tables when we run LHMs which is to be expected, but it would be nice if LHM were able to monitor how hard it was pushing the cluster and back off if it got to be too hard. This would be at the expense of how long the migration took to run, but I think I'd rather a longer running migration which could come closer to guaranteeing our replication lag would remain inside some threshold. 

If you guys don't want to add this or don't think you'll find the time would you give me some pointers on how I might accomplish it? Thanks!

**Comment by arthurnn** [comment]
we merged a LagThrottle into master, which should solve this.
thanks all
