### ISSUE TITLE
Document how to set a default column value in README

### ISSUE THREAD

**Issue by zmillman** [soundcloud/lhm#61]
It would be great to have an example of the project README of how to add a column with a default value.

**Comment by qoyyim** [comment]
:+1:

**Comment by arthurnn** [comment]
👍  @zmillman fell free to open a PR with the doc change.

**Comment by cte** [comment]
For those that came here via Google looking for an answer, you can find one [here](http://stackoverflow.com/questions/35599321/add-column-with-default-in-lhm-large-hadron-migrator) (StackOverflow).
