### ISSUE TITLE
Temporary tables are not cleaned up automatically

### ISSUE THREAD

**Issue by shaqq** [soundcloud/lhm#95]
Even if the migration runs successfully, it seems like the temporary tables remain. I have to manually call `Lhm.cleanup(true)` after each migration.

**Comment by shaqq** [comment]
Rather, the _backup_ tables remain.

**Comment by arthurnn** [comment]
thats by design. 
What I do to automate that is, I have a rake task that runs the LHM and after runs the cleanup.
